### ISSUE TITLE
k8s에 배포 시 리액트에서 환경 변수를 읽어오지 못하는 이슈

### ISSUE THREAD

**Issue by SSUK-H** [ssap-rainbow/SSAP-FrontEnd#6]
## 작업 사항

>  카카오 로그인 환경 변수를 k8s에 ConfigMap과 Secret에 Key:Value 형태로 등록 후 배포 (Frontend.yaml(deployment)에 ConfigMap과 Secret 정보를 읽도록 셋팅 후 배포) 하였습니다.

## 에러 내용

> 리액트에서 환경 변수를 읽어오지 못하는 오류가 발생하였습니다.

## 에러 원인

> React는 런타임방식으로 환경변수를 읽어오지 못하고, 빌드 단계에서 환경변수 정보를 읽어와야 해서 undefind가 뜨게 되었습니다.

## 기타 사항

> 배포 파일 참고 reop: https://github.com/ssap-rainbow/DKOS_Test_Backend.git

**Comment by SSUK-H** [comment]
REACT_APP_REST_API_KEY가 노출되면 안되기에 도커 파일에 ARG와 ENV 설정도 해보고.. 여러 시도를 해보다 다른 방법이 있을까 문의를 해보았지만.. 로컬에서 빌드 후 깃허브에 올리는 방법으로 제시해 주셨습니다. 결국 .env.production을 추가해서 깃허브에 올려서 빌드해서 해결 완료 하였습니다.

**Comment by ssap-rainbow** [comment]
결국 .env.production을 추가해서 깃허브에 올려서 빌드해서 해결 완료 하였습니다.

**Comment by cipp00h** [comment]
결국 .env.production을 추가해서 깃허브에 올려서 빌드해서 해결 완료 하였습니다.

**Comment by SSUK-H** [comment]
이틀 동안 아주 고생 많으셨습니다!! 👍

**Comment by ExceptAnyone** [comment]
성숙석은 폼 미쳐따이~
