### ISSUE TITLE
React 페이지 새로고침 및 주소창에 특정 URI 직접 접근 시 404 에러 페이지 출력

### ISSUE THREAD

**Issue by cipp00h** [ssap-rainbow/SSAP-FrontEnd#8]
## 작업 사항

> React 페이지 새로고침 및 주소창에 특정 URI 직접 접근 시 404 에러 페이지 출력 문제 수정

## 에러 내용 [이미지]

> React 페이지에서 새로고침(F5)을 하면 404 에러 페이지 출력
>  주소창에 특정 URI 직접 접근 시 404 에러 페이지 출력
![image](https://github.com/ssap-rainbow/SSAP-FrontEnd/assets/33807391/011d5c41-5c1e-44e2-ab3d-dab55eca33f5)

## 에러 원인

> React 실행 시 -s 옵션을 추가 하지 않아 문제 발생. 

## 기타 사항

> 기타 사항을 작성해주세요

**Comment by SSUK-H** [comment]
"-s" : 어떤 라우팅을 하더라도 index.hml을 찾도록 함.
와... -S의 소중함을 알게되었네요..😇
고생하셨습니다 ㅠㅠ
